### ISSUE TITLE
Initially select bold and typing text results bold unselect.

### ISSUE THREAD

**Issue by sunilsharma2** [fleather-editor/fleather#281] opened 2024-02-15 05:40 UTC
On the very first on select bold or italic fleather toolbar and start typing the bold or italic unselect issue. On again select bold or italic it works fine with bold text.
Kindly look into this.

**Comment by amantoux** [comment] 2024-02-15 08:40
@sunilsharma2 can you please re phrase your example? I cannot reproduce.

**Comment by sunilsharma2** [comment] 2024-02-17 08:15
@amantoux when I focus on fleather editor box, select bold and start typing bold automatically unselected and plainText written.

**Comment by amantoux** [comment] 2024-02-17 08:42
we need more details
What platform? what version of Flutter? what version of Fleather

**Comment by sunilsharma2** [comment] 2024-02-20 07:42
@amantoux 
Flutter version 3.16.0
Dart 3.2.0
Fleather 1.14.1

**Comment by Amir-P** [comment] 2024-02-21 16:48
I wasn't able to reproduce using `flutter: 3.16.9` and `fleather 1.14.1`. Please include a minimal reproducible sample code. @sunilsharma2 


https://github.com/fleather-editor/fleather/assets/8766492/1703ca51-284b-4284-88de-f3cdb6190f3f

**Comment by amantoux** [comment] 2024-03-04 18:17
Closing this as no further activity for last couple of weeks

**Closed by amantoux** 2024-03-04 18:17 UTC
Labels: waiting for user feedback
