### ISSUE TITLE
When toggling colour selection on Toolbar, assertion received

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#290] opened 2024-03-03 15:09 UTC
## Steps to Reproduce

1. I use the toolbar as an overlay itself, a bit like Notion. However, when I toggle text colour option, I get the following assertion:

```
flutter: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 168 pos 12: '_overlay != null': is not true.
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:168:12)
#3      SelectorScopeState.pushSelector.<anonymous closure> (package:fleather/src/widgets/editor_toolbar.dart:1259:20)
#4      _RootZone.run (dart:async/zone.dart:1655:54)
#5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:205:18)
#6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:816:39)
#7      Future._propagateToListeners (dart:async/future_impl.dart:872:11)
#8      Future._propagateToListeners (dart:async/future_impl.dart:771:9)
#9      Future._completeWithValue (dart:async/future_impl.dart:647:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

flutter: ----------------------------------------------------
```
The colour selection menu does not open. 

## Environment
- MacOS
- Flutter version 3.16.4
- Fleather version 1.14.1

**Comment by Amir-P** [comment] 2024-03-16 09:12
Could you please provide a minimal code that reproduces the issue? @nialljawad96

**Comment by nialljawad96** [comment] 2024-03-16 12:43
@Amir-P Here's an example using OverlayEntry. If you then click on the text colour option on the toolbar, it receives the assertion outlined before.

```
  OverlayEntry? overlayEntry;

   overlayEntry = OverlayEntry(
          builder: (BuildContext context) {
            return Positioned(
                left: toolbarPosition!.dx - 50,
                top: toolbarPosition!.dy - 40,
                child: FadeInWidget(
                  child: Column(
                      children: [
                        Material(
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(5),
                              color: Colors.black,
                            ),
                            width: 500,
                            height: 30,
                            child: Padding(
                              padding: const EdgeInsets.only(left: 2.0, right: 2.0, top: 3.0, bottom: 3.0),
                              child: FleatherToolbar.basic(
                                controller: controller,
                                hideLink: true,
                              ),
                            ),
                          ),
                        ),
                      ]),
                ));
          },
        );

        Overlay.of(context).insert(overlayEntry!);
```

**Comment by Amir-P** [comment] 2024-03-27 16:52
Unfortunately, this is not a runnable code. It would help me a lot if you were able to provide a completely runnable minimal code that reproduces the issue. @nialljawad96

**Comment by amantoux** [comment] 2024-04-15 07:19
Closing this as no reproducible test case provided
Feel free to re-open

**Comment by nialljawad96** [comment] 2024-04-27 09:55
@Amir-P Thanks Amir. I'm not getting the assertion anymore, but the issue remains whereby I can't open that colour selection box without it immediately closing. Here's reproducible code:

```
import 'package:flutter/material.dart';
import 'package:fleather/fleather.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(

        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: MyHomePage(title: 'Fleather Test'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({super.key, required this.title});

  final String title;


  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  FleatherController controller = FleatherController(document: ParchmentDocument());
  int _counter = 0;

  void testToolbar() {

    OverlayEntry? overlayEntry;

    overlayEntry = OverlayEntry(
      builder: (BuildContext context) {
        return Positioned(
            left: 50,
            top: 40,
            child: Column(
                  children: [
                    Material(
                      child: Padding(
                        padding: const EdgeInsets.only(left: 2.0, right: 2.0, top: 3.0, bottom: 3.0),
                        child: FleatherToolbar.basic(
                          controller: controller,
                          hideLink: true,
                        ),
                      ),
                    ),
                  ]),
            );
      },
    );

    Overlay.of(context).insert(overlayEntry);
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,

        title: Text(widget.title),
      ),
      body: Center(

        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: testToolbar,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```

**Comment by Amir-P** [comment] 2024-04-27 13:34
This is happening since we're calling `removeEntry` when toolbar gets rebuilt and I can't find a reason for doing so. Will remove it in the PR and see what @amantoux thinks. @nialljawad96

**Comment by nialljawad96** [comment] 2024-04-27 14:07
@Amir-P Awesome thanks!

**Closed** 2024-04-28 07:18 UTC
