### ISSUE TITLE
It seems the new overlay usage in heading and color picking etc doesnt work when keyboard is active

### ISSUE THREAD

**Issue by ember11498** [fleather-editor/fleather#317] opened 2024-04-08 21:34 UTC
Is this a known bug? when keyboard is active the overlay throwing an exception when i tap on headings or color picker

**Comment by amantoux** [comment] 2024-04-08 21:38
I could not reproduce 
Can you please give more details
(Fleather version, Flutter version, platform)?

**Comment by ember11498** [comment] 2024-04-14 20:23
E/flutter ( 7078): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
    E/flutter ( 7078): #0      SelectorScope.of (package:fleather/src/widgets/editor_toolbar.dart:1234:60)
    E/flutter ( 7078): #1      _ColorButtonState._defaultPickColor (package:fleather/src/widgets/editor_toolbar.dart:424:26)
    E/flutter ( 7078): #2      _ColorButtonState.build.<anonymous closure> (package:fleather/src/widgets/editor_toolbar.dart:480:78)
    E/flutter ( 7078): #3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
    E/flutter ( 7078): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
    E/flutter ( 7078): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
    E/flutter ( 7078): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
    E/flutter ( 7078): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:279:7)
    E/flutter ( 7078): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:167:27)
    E/flutter ( 7078): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:499:20)
    E/flutter ( 7078): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
    E/flutter ( 7078): #11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
    E/flutter ( 7078): #12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
    E/flutter ( 7078): #13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
    E/flutter ( 7078): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
    E/flutter ( 7078): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
    E/flutter ( 7078): #16     _invoke1 (dart:ui/hooks.dart:328:13)
    E/flutter ( 7078): #17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
    E/flutter ( 7078): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)

`    class FleatherTextEditor extends StatefulWidget {
      final ParchmentDocument doc;
      final Function(FleatherController) onSaved;

      const FleatherTextEditor(
          {super.key, required this.doc, required this.onSaved});

      @override
      State<FleatherTextEditor> createState() => _FleatherTextEditorState();
    }

    class _FleatherTextEditorState extends State<FleatherTextEditor> {
      late final FleatherController controller;

      @override
      void initState() {
        super.initState();
        controller = FleatherController(document: widget.doc);
        widget.doc.changes.listen((event) {
          print(controller.document.length);
        });
      }

      Widget backgroundColorBuilder(context, value) => Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(
                Icons.mode_edit_outline_outlined,
                size: 16,
              ),
              Container(
                width: 18,
                height: 4,
                decoration: BoxDecoration(color: value),
              )
            ],
          );
      Widget textColorBuilder(context, value) {
        Color effectiveColor =
            value ?? DefaultTextStyle.of(context).style.color ?? Colors.black;
        return Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(
              Icons.text_fields_sharp,
              size: 16,
            ),
            Container(
              width: 18,
              height: 4,
              decoration: BoxDecoration(color: effectiveColor),
            )
          ],
        );
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          resizeToAvoidBottomInset: true,
          body: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 600),
            child: SafeArea(
              child: CustomFleatherTheme(
                child: Column(
                  children: [
                    ElevatedButton(
                      onPressed: () {
                        widget.onSaved(controller);
                        context.pop();
                      },
                      style: ButtonStyle(
                        backgroundColor:
                            MaterialStatePropertyAll(context.colorScheme.primary),
                      ),
                      child: Text('Save', style: context.regular),
                    ),
                    Expanded(
                      child: FleatherEditor(
                        controller: controller,
                        autofocus: true,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 8,
                        ),
                      ),
                    ),
                    KeyboardVisibilityBuilder(
                      builder: (p0, isKeyboardVisible) {
                        if (isKeyboardVisible) {
                          return SizedBox(
                            width: MediaQuery.of(context).size.width,
                            child: SingleChildScrollView(
                              scrollDirection: Axis.horizontal,
                              child: Row(
                                children: [
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.bold,
                                    icon: Icons.format_bold,
                                    controller: controller,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.italic,
                                    icon: Icons.format_italic,
                                    controller: controller,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.underline,
                                    icon: Icons.format_underline,
                                    controller: controller,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.strikethrough,
                                    icon: Icons.format_strikethrough,
                                    controller: controller,
                                  ),
                                  ColorButton(
                                    controller: controller,
                                    attributeKey:
                                        ParchmentAttribute.foregroundColor,
                                    nullColorLabel: 'Automatic',
                                    builder: textColorBuilder,
                                  ),
                                  ColorButton(
                                    controller: controller,
                                    attributeKey:
                                        ParchmentAttribute.backgroundColor,
                                    nullColorLabel: 'No color',
                                    builder: backgroundColorBuilder,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.left,
                                    icon: Icons.format_align_left,
                                    controller: controller,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.center,
                                    icon: Icons.format_align_center,
                                    controller: controller,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.right,
                                    icon: Icons.format_align_right,
                                    controller: controller,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.justify,
                                    icon: Icons.format_align_justify,
                                    controller: controller,
                                  ),
                                  IndentationButton(
                                    increase: false,
                                    controller: controller,
                                  ),
                                  IndentationButton(
                                    controller: controller,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.block.numberList,
                                    controller: controller,
                                    icon: Icons.format_list_numbered,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.block.bulletList,
                                    controller: controller,
                                    icon: Icons.format_list_bulleted,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.block.checkList,
                                    controller: controller,
                                    icon: Icons.checklist,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.block.code,
                                    controller: controller,
                                    icon: Icons.code,
                                  ),
                                  ToggleStyleButton(
                                    attribute: ParchmentAttribute.block.quote,
                                    controller: controller,
                                    icon: Icons.format_quote,
                                  ),
                                  InsertEmbedButton(
                                    controller: controller,
                                    icon: Icons.horizontal_rule,
                                  ),
                                  SelectHeadingButton(controller: controller),
                                  UndoRedoButton.undo(controller: controller),
                                  UndoRedoButton.redo(controller: controller),
                                ],
                              ),
                            ),
                          );
                        }
                        return const SizedBox();
                      },
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      }
    }
`

**Comment by ember11498** [comment] 2024-04-14 21:31
after some experiences I found that the overlay does not consider the fact that keyboard might be active. per example in my case I place my toolbar right above the keyboard and when I tap on colorbutton the overlay is behind the keyboard (i cannot see it). if i place the toolbar at the top of the screen i can see it. but i want the toolbar to be right next the keyboard so if it is possible is there a way you can implement something that will take into consideration the keyboard height or something?

    class FleatherTextEditor extends StatefulWidget {
      final ParchmentDocument doc;
      final Function(FleatherController) onSaved;

      const FleatherTextEditor(
          {super.key, required this.doc, required this.onSaved});

      @override
      State<FleatherTextEditor> createState() => _FleatherTextEditorState();
    }

    class _FleatherTextEditorState extends State<FleatherTextEditor> {
      late final FocusNode node;
      late final FleatherController controller;

      @override
      void initState() {
        super.initState();
        node = FocusNode();
        controller = FleatherController(document: widget.doc);
        widget.doc.changes.listen((event) {
          print(controller.document.length);
        });
      }

      Widget backgroundColorBuilder(BuildContext context, value) => Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(
                Icons.mode_edit_outline_outlined,
                size: 16,
              ),
              Container(
                width: 18,
                height: 4,
                decoration: BoxDecoration(color: value),
              )
            ],
          );
      Widget textColorBuilder(BuildContext context, value) {
        Color effectiveColor =
            value ?? DefaultTextStyle.of(context).style.color ?? Colors.black;
        return Column(
          mainAxisAlignment: MainAxisAlignment.center,
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(
              Icons.text_fields_sharp,
              size: 16,
            ),
            Container(
              width: 18,
              height: 4,
              decoration: BoxDecoration(color: effectiveColor),
            )
          ],
        );
      }

      @override
      Widget build(BuildContext context) {
        return Scaffold(
          resizeToAvoidBottomInset: true,
          body: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 600),
            child: SafeArea(
              child: CustomFleatherTheme(
                child: Column(
                  children: [
                    ElevatedButton(
                      onPressed: () {
                        widget.onSaved(controller);
                        context.pop();
                      },
                      style: ButtonStyle(
                        backgroundColor:
                            MaterialStatePropertyAll(context.colorScheme.primary),
                      ),
                      child: Text('Save', style: context.regular),
                    ),
                    FleatherToolbar(
                      children: [
                        ColorButton(
                          controller: controller,
                          attributeKey: ParchmentAttribute.foregroundColor,
                          nullColorLabel: 'Automatic',
                          builder: (context, color) =>
                              textColorBuilder(context, color),
                        ),
                      ],
                    ),
                    Expanded(
                      child: FleatherEditor(
                        controller: controller,
                        focusNode: node,
                        autofocus: true,
                        padding: const EdgeInsets.symmetric(
                          horizontal: 8,
                        ),
                      ),
                    ),
                    KeyboardVisibilityBuilder(
                      builder: (p0, isKeyboardVisible) {
                        if (isKeyboardVisible) {
                          return SizedBox(
                            width: MediaQuery.of(context).size.width,
                            height: 35,
                            child: FleatherToolbar(
                              padding: const EdgeInsets.all(0),
                              children: [
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.bold,
                                  icon: Icons.format_bold,
                                  controller: controller,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.italic,
                                  icon: Icons.format_italic,
                                  controller: controller,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.underline,
                                  icon: Icons.format_underline,
                                  controller: controller,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.strikethrough,
                                  icon: Icons.format_strikethrough,
                                  controller: controller,
                                ),
                                ColorButton(
                                  controller: controller,
                                  attributeKey: ParchmentAttribute.foregroundColor,
                                  nullColorLabel: 'Automatic',
                                  builder: (context, color) =>
                                      textColorBuilder(context, color),
                                ),
                                ColorButton(
                                  controller: controller,
                                  attributeKey: ParchmentAttribute.backgroundColor,
                                  nullColorLabel: 'No color',
                                  builder: backgroundColorBuilder,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.left,
                                  icon: Icons.format_align_left,
                                  controller: controller,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.center,
                                  icon: Icons.format_align_center,
                                  controller: controller,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.right,
                                  icon: Icons.format_align_right,
                                  controller: controller,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.justify,
                                  icon: Icons.format_align_justify,
                                  controller: controller,
                                ),
                                IndentationButton(
                                  increase: false,
                                  controller: controller,
                                ),
                                IndentationButton(
                                  controller: controller,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.block.numberList,
                                  controller: controller,
                                  icon: Icons.format_list_numbered,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.block.bulletList,
                                  controller: controller,
                                  icon: Icons.format_list_bulleted,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.block.checkList,
                                  controller: controller,
                                  icon: Icons.checklist,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.block.code,
                                  controller: controller,
                                  icon: Icons.code,
                                ),
                                ToggleStyleButton(
                                  attribute: ParchmentAttribute.block.quote,
                                  controller: controller,
                                  icon: Icons.format_quote,
                                ),
                                InsertEmbedButton(
                                  controller: controller,
                                  icon: Icons.horizontal_rule,
                                ),
                                SelectHeadingButton(controller: controller),
                                UndoRedoButton.undo(controller: controller),
                                UndoRedoButton.redo(controller: controller),
                              ],
                            ),
                          );
                        }
                        return const SizedBox();
                      },
                    ),
                  ],
                ),
              ),
            ),
          ),
        );
      }
    }

**Comment by ironCheng** [comment] 2024-04-18 09:26
![Simulator Screenshot - iPhone 15 Pro - 2024-04-18 at 17 16 59](https://github.com/fleather-editor/fleather/assets/16793140/38627c04-c2ff-488e-a4d3-117027582909)

<img width="934" alt="截屏2024-04-18 17 22 23" src="https://github.com/fleather-editor/fleather/assets/16793140/def30232-2ea7-4eb8-8a12-256969aba746">

I added a spreadUp attribute to customFleatherThemeData.
Then modified the _selectHeading() method of the editor_toolbar.dart file

`Positioned(
        bottom: MediaQuery.of(context).size.height - originOffset.dy,
        left: offset.dx,
        child: selector,
      )`

**Comment by ironCheng** [comment] 2024-04-18 09:29
<img width="667" alt="截屏2024-04-18 17 28 47" src="https://github.com/fleather-editor/fleather/assets/16793140/ba120281-eeba-4ec6-ade4-94cb66a6666d">

**Comment by ember11498** [comment] 2024-04-22 09:56
@ironCheng I see you resolved the issue but that spreadUp parameter doesnt exist. Will there be a pull request? Or I need to somehow customize it on my own like you did?

**Comment by ember11498** [comment] 2024-04-22 10:00
@Amir-P can you had this feature to the package?

**Comment by Amir-P** [comment] 2024-04-22 10:06
Sorry for the delay and thanks for reporting the issue and discussing possible solutions. @ironCheng @ember11498 
An extra parameter to control the direction in which overlay is opened is good, but I think it's better to take a more flexible approach like the one being already used in `showMenu` by Flutter (positioning overlay according to the available space and media query details). I will work on it this week and open the PR.

**Comment by Amir-P** [comment] 2024-04-26 16:28
Could you please check the fix and verify if it's working correctly for you? @ironCheng @ember11498 

```yaml
  fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: fix/toolbar_selector_positioning
      path: packages/fleather
```

**Comment by ironCheng** [comment] 2024-04-29 10:08
I found fix/toolbar_selector_positioning is deleted, it seems you merged to the mastr?  So I verified in the master branch, it still have problem.

![WechatIMG54](https://github.com/fleather-editor/fleather/assets/16793140/6db2e726-63fa-4e43-95a9-851ecc8ec938)


My test code:
<img width="722" alt="截屏2024-04-29 18 06 35" src="https://github.com/fleather-editor/fleather/assets/16793140/d342efe9-4776-4dd8-be94-086c06b48836">

**Comment by Amir-P** [comment] 2024-05-13 09:00
Could you test against #352? @ironCheng 

```yaml
 fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: fix/selector_going_under_keyboard
      path: packages/fleather
```

**Comment by ironCheng** [comment] 2024-05-13 13:47
I'm coming. It test great！🎉
But maybe the Y minus the height of the toolbar will be more better.   @Amir-P 


![1715607958206](https://github.com/fleather-editor/fleather/assets/16793140/af95f953-dcf7-4217-a4d1-463ab2b58bfd)

![1715607859269](https://github.com/fleather-editor/fleather/assets/16793140/097f5d19-f271-4924-9511-5e86cb71fcdb)

**Comment by ember11498** [comment] 2024-06-12 09:48
can you merge this? i just tested the latest version and this is still a bug

**Closed** 2024-06-15 12:29 UTC
Labels: bug
